my-jenkins-server:
  build: .
  environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
  container_name: pres
  ports:
      - "50000:50000"
      - "8080:8080"
  volumes:
      - /data/jenkins_home:/var/jenkins_home
